# Generated by Django 5.0.7 on 2024-07-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='board_comment',
        ),
    ]
